### ISSUE TITLE
React Event Binding

### ISSUE THREAD

**Issue by ghost** [alekspopovic/task-management-app#1]
Sorry for creating this as an issue i am a beginner in react, followed one of your videos on youtube. i have hard time understanding the  code in statusLine.js where in you are passing the moveTask property to Task component where is the id,status coming from

`taskList = taskForStatus.map((task) => {
            return (
                <Task                   
                    moveTask={(id,status) => {  
                        console.log(status);
                        return moveTask(id,status)
                    }}
                />
            )
        })
   `             
    can i not write it this way `moveTask={moveTask.bind(null,task.id,status)}`

**Comment by alekspopovic** [comment]
Thank you for bringing this to my attention, and opening an issue is totally fine, no worries!

You can actually leave out the (id, status) from that line, and just write it like this:

**Comment by alekspopovic** [comment]
Thank you for bringing this to my attention, and opening an issue is totally fine, no worries!

You can actually leave out the (id, status) from that line, and just write it like this:

return (
        <Task
          addTask={(task) => addTask(task)}
          deleteTask={deleteTask}
          moveTask={moveTask}
          key={task.id}
          task={task}
        />
      );

We are getting the id and status from inside the Task component (from the 'task' prop). Since we are just passing in the function as a parameter the function's own parameters are not relevant for this line, so this is a slight oversight on my part. Sorry for confusing you!

I hope that clears it up for you. Please let me know if you need any more help with this code.

**Comment by alekspopovic** [comment]
Both deleteTask and moveTask functions work that way. We define the function parameters in App.js where functions are declared and we pass them in from inside the Task component. They are not needed in StatusLine component because we are just passing in the function as a prop.

**Comment by ghost** [comment]
so why it was not working when i was passing it this way `moveTask={moveTask.bind(null,task.id,status)}`
is the wrong way to use bind or its useless in this situation?.
and is there any specfic term for such statements  `(id,status) => moveTask(id,status) ` what is such concpets called so i can learn more on this

 Thanks for replying

**Comment by alekspopovic** [comment]
Bind is not going to work in a case like this because it's intended for class components (and 'this' keyword used in them). All of my projects use function components, so bind won't work. In general the whole React ecosystem is moving away from using class components.

> and is there any specfic term for such statements `(id,status) => moveTask(id,status) ` what is such concpets called so i can learn more on this

It's an 'arrow' function, which is in this case used as a wrapper function for moveTask (although unnecessarily). It's a super useful JavaScript feature.

You can read more about arrow functions here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

You are welcome and good luck with your React journey!

**Comment by ghost** [comment]
Thanks You Are Awesome
